/// Segment Dimension
table Segment
	lineageTag: bef8381c-0370-4de2-890a-272a05eb1cfb

	column Segment
		dataType: string
		lineageTag: db2b1db1-3659-4861-a83a-61f3255bc381
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column SegmentID
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 48c09110-75d2-4361-abdc-db03df45e493
		summarizeBy: none
		sourceColumn: SegmentID

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition Segment = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(Web.Contents("https://ms365pk-my.sharepoint.com/personal/mustafa_ms365_com_pk/Documents/Temp/Financial%20Sample.xlsx"), null, true),
				    financials_Table = Source{[Item="financials",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(financials_Table,{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Changed Type",{"Segment"}),
				    #"Removed Duplicates" = Table.Distinct(#"Removed Other Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Added Index",{{"Index", "SegmentID"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

